[package]
name = "videohub"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
thiserror = "1"


[workspace]
members = ["cli/", "web-server/", "web-server/frontend"]
