[package]
name = "videohub-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
yew = "0.19"
web-sys = { version="0.3.58", features=["CssStyleDeclaration", "HtmlElement", "HtmlButtonElement"] }
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }