[package]
name = "videohub-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
videohub = { path = "../" }
serde_json = "1"
tera = "1"
itertools = "0.10"
clap = { version = "3.2", features = ["derive"] }
log = "0.4"
simple_logger = "2.2"
anyhow = "1"
